+incdir+rtl/include
rtl/include/agni_pkg.sv
rtl/common/fifo.sv
rtl/common/async_fifo.sv
rtl/common/ram_sp.sv
rtl/common/ram_dp.sv
rtl/common/arbiter_rr.sv
rtl/common/cdc_sync.sv
rtl/common/reset_sync.sv
rtl/common/encoder_onehot.sv
rtl/common/decoder_onehot.sv
rtl/compute/fma_unit.sv
rtl/compute/fp32_alu.sv
rtl/compute/int32_alu.sv
rtl/compute/sfu.sv
rtl/compute/tensor_core.sv
rtl/sm/warp_scheduler.sv
rtl/sm/register_file.sv
rtl/sm/dispatch_unit.sv
rtl/sm/operand_collector.sv
rtl/sm/streaming_multiprocessor.sv
rtl/memory/ecc_encoder.sv
rtl/memory/ecc_decoder.sv
rtl/memory/chipkill_ecc.sv
rtl/memory/tag_array.sv
rtl/memory/l1_cache.sv
rtl/memory/l2_cache_slice.sv
rtl/memory/hbm4_controller.sv
rtl/noc/noc_router.sv
rtl/noc/noc_mesh.sv
rtl/power/clock_gate.sv
rtl/power/dvfs_controller.sv
rtl/power/thermal_monitor.sv
rtl/power/pll_model.sv
rtl/io/pcie_gen6_phy.sv
rtl/io/nvlink_phy.sv
rtl/gpc/gpc.sv
rtl/top/agni_gpu_top.sv
